name: Build Flutter APK & AAB

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Structure
        run: |
          flutter create temp_app --platforms=android --org=com.wasalni.app
          cp -r temp_app/android .
          rm -rf temp_app

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK (For Testing on Phone)
        run: flutter build apk --release

      - name: Build App Bundle (For Google Play)
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release-apk.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
